slot_to_slot_name = {
    "gloves": "Hands",
    "hands": "Hands",
    "neck": "Neck",
    "necks": "Neck",
    "wrist": "Wrist",
    "wrists": "Wrist",
    "rings": "Finger",
    "finger": "Finger",
    "shoulder": "Shoulder",
    "shoulders": "Shoulder",
    "sigil": "Relic",
    "sigils": "Relic",
    "totems": "Relic",
    "idol": "Relic",
    "idols": "Relic",
    "libram": "Relic",
    "librams": "Relic",
    "relic": "Relic",
    "relics": "Relic",
    "head": "Head",
    "heads": "Head",
    "helm": "Head",
    "helmets": "Head",
    "back": "Back",
    "backs": "Back",
    "legs": "Legs",
    "feet": "Feet",
    "chest": "Chest",
    "chests": "Chest",
    "trinket": "Trinket",
    "trinkets": "Trinket",
    "waist": "Waist",
    "waists": "Waist",
    "wand": "Ranged",
    "wands": "Ranged",
    "ranged": "Ranged",
    "ranged weapon": "Ranged",
    "ranged weapons": "Ranged",
    "guns and bows": "Ranged",
}

spec_to_slots = {
    "blood-tank-death-knight": {
        "1-hander weapons": "Weapon 1H",
        "2-hander weapons": "Weapon 2H",
        "weapon": "Weapon 2H",
        "2-handed weapons": "Weapon 2H",
        "1-hand weapons": "Weapon 1H",
    },
    "frost-death-knight": {
        "off hand weapons": "Off hand",
        "main hand weapons": "Weapon",
        "off-hand weapon": "Off hand",
        "main-hand weapon": "Weapon",
    },
    "unholy-death-knight": {
        "off hand weapons": "Off hand",
        "main hand weapons": "Weapon",
        "off-hand weapon": "Off hand",
        "main-hand weapon": "Weapon",
    },
    "balance-druid": {
        "off-hand weapons": "Off hand",
        "main hand weapons": "Weapon 1H",
        "two-handed weapons": "Weapon 2H",
        "off-hand weapon": "Off hand",
        "main-hand weapon": "Weapon 1H",
    },
    "feral-tank-druid": {
        "weapons": "Weapon",
        "weapon": "Weapon",
    },
    "feral-dps-druid": {
        "weapons": "Weapon",
        "weapon": "Weapon",
    },
    "restoration-druid": {
        "off hand weapons": "Off hand",
        "main hand weapons": "Weapon 1H",
        "two-handed weapons": "Weapon 2H",
        "two hand weapon": "Weapon 2H",
        "off-hand": "Off hand",
        "main-hand weapon": "Weapon 1H",
    },
    "beast-mastery-hunter": {
        "one-handed weapons": "Weapon 1H",
        "two-hand weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 2H",
    },
    "marksmanship-hunter": {
        "one-handed weapons": "Weapon 1H",
        "two-hand weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 2H",
    },
    "survival-hunter": {
        "one-handed weapons": "Weapon 1H",
        "two-hand weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 2H",
    },
    "arcane-mage": {
        "off hand weapons": "Off hand",
        "main-hand and two-handed weapons": "Weapon",
        "main-hand weapon": "Weapon",
    },
    "fire-mage": {
        "off hand weapons": "Off hand",
        "main-hand and two-handed weapons": "Weapon",
        "main-hand weapon": "Weapon",
        "off-hand weapon": "Off hand"
    },
    "frost-mage": {
        "off hand weapons": "Off hand",
        "main-hand and two-handed weapons": "Weapon",
        "main-hand weapon": "Weapon",
    },
    "holy-paladin": {
        "main-hand weapons": "Weapon",
        "shields and off-hands": "Off hand",
        "main-hand weapon": "Weapon",
        "shield": "Off hand",
        "main hand weapons": "Weapon",
    },
    "protection-paladin": {
        "weapons": "Weapon",
        "shields": "Off hand",
        "main-hand weapon": "Weapon",
        "shield": "Off hand",
        "weapons and offhands": "Weapon",
    },
    "retribution-paladin": {
        "two hand weapons": "Weapon",
        "two-hand weapon": "Weapon",
        "weapon": "Weapon"
    },
    "discipline-priest": {
        "off-hands": "Off hand",
        "main and two-handed weapons": "Weapon",
        "off-hand weapon": "Off hand",
        "main-hand weapon": "Weapon",
    },
    "holy-priest": {
        "off-hands": "Off hand",
        "main and two-handed weapons": "Weapon",
        "off-hand weapon": "Off hand",
        "main-hand weapon": "Weapon",
        "trinket - sustain": "Trinket",
        "trinket - throughput": "Trinket",
        "two-hand weapon": "Weapon"
    },
    "shadow-priest": {
        "off hands": "Off hand",
        "main hand weapons": "Weapon 1H",
        "two-handed weapons": "Weapon 2H",
        "off-hand weapon": "Off hand",
        "main-hand weapon": "Weapon 1H",
        "off-hands": "Off hand",
    },
    "assassination-rogue": {
        "weapons": "Weapon",
        "main-hand weapon": "Weapon",
        "off-hand weapon": "Weapon",
    },
    "combat-rogue": {
        "off hand weapons": "Off hand",
        "main hand weapons": "Weapon",
        "off-hand weapon": "Off hand",
        "main-hand weapon": "Weapon",
    },
    "elemental-shaman": {
        "shields / off-hands": "Off hand",
        "weapons": "Weapon",
        "off-hand": "Off hand",
        "main-hand weapon": "Weapon",
    },
    "enhancement-shaman": {
        "weapons": "Weapon",
        "main-hand weapon": "Weapon",
        "off-hand weapon": "Weapon",
    },
    "restoration-shaman": {
        "shields / off-hands": "Off hand",
        "weapons": "Weapon",
        "shield": "Off hand",
        "main-hand weapon": "Weapon",
        "off-hand": "Off hand"
    },
    "affliction-warlock": {
        "offhand": "Off hand",
        "1-handed weapons": "Weapon 1H",
        "2-handed weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 2H",
        "weapon": "Weapon 2H",
        "off-hand weapon": "Off hand"
    },
    "demonology-warlock": {
        "offhand": "Off hand",
        "1-handed weapons": "Weapon 1H",
        "2-handed weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 2H",
        "weapon": "Weapon 2H",
        "off-hand weapon": "Off hand"
    },
    "destruction-warlock": {
        "offhand": "Off hand",
        "1-handed weapons": "Weapon 1H",
        "2-handed weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 2H",
        "weapon": "Weapon 2H",
        "main-hand": "Weapon 1H",
        "off-hand": "Off hand"
    },
    "arms-warrior": {
        "two handed weapons": "Weapon",
        "main-hand weapon": "Weapon",
    },
    "fury-warrior": {
        "two handed weapons": "Weapon",
        "main-hand weapon": "Weapon",
        "off-hand weapon": "Weapon",
    },
    "protection-warrior": {
        "shields": "Off hand",
        "one-handed weapons": "Weapon",
        "shield": "Off hand",
        "main-hand weapon": "Weapon",
        "ranged weapons": "Ranged",
    },
}
