gear_planner_slots = {
    "1": "Head",
    "2": "Neck",
    "3": "Shoulder",
    "15": "Back",
    "5": "Chest",
    "9": "Wrist",
    "10": "Hands",
    "6": "Waist",
    "7": "Legs",
    "8": "Feet",
    "11": "Finger",
    "12": "Finger",
    "13": "Trinket",
    "14": "Trinket",
    "16": "Weapon",
    "17": "Off hand",
    "18": "Relic"
}

slot_to_slot_name = {
    "gloves": "Hands",
    "hands": "Hands",
    "hand": "Hands",
    "neck": "Neck",
    "necks": "Neck",
    "wrist": "Wrist",
    "wrists": "Wrist",
    "bracer": "Wrist",
    "rings": "Finger",
    "ring": "Finger",
    "finger": "Finger",
    "shoulder": "Shoulder",
    "shoulders": "Shoulder",
    "sigil": "Relic",
    "sigils": "Relic",
    "totems": "Relic",
    "idol": "Relic",
    "idols": "Relic",
    "libram": "Relic",
    "librams": "Relic",
    "relic": "Relic",
    "relics": "Relic",
    "head": "Head",
    "heads": "Head",
    "helm": "Head",
    "helmets": "Head",
    "back": "Back",
    "backs": "Back",
    "cloak": "Back",
    "legs": "Legs",
    "leg": "Legs",
    "feet": "Feet",
    "boots": "Feet",
    "chest": "Chest",
    "chests": "Chest",
    "trinket": "Trinket",
    "trinkets": "Trinket",
    "waist": "Waist",
    "belt": "Waist",
    "waists": "Waist",
    "wand": "Ranged",
    "wands": "Ranged",
    "ranged": "Ranged",
    "weapons": "Weapon",
    "ranged weapon": "Ranged",
    "ranged weapons": "Ranged",
    "guns and bows": "Ranged",
}

spec_to_slots = {
    "blood-tank-death-knight": {
        "1-hander weapons": "Weapon 1H",
        "2-hander weapons": "Weapon 2H",
        "2-hander": "Weapon 2H",
        "weapon": "Weapon",
        "2-handed weapons": "Weapon 2H",
        "1-hand weapons": "Weapon 1H",
        "defensive trinkets": "Trinket",
        "offensive trinkets": "Trinket Off",
    },
    "frost-death-knight": {
        "off hand weapons": "Off hand",
        "main hand weapons": "Weapon 1H",
        "off-hand weapon": "Off hand",
        "off-hand weapons": "Off hand",
        "main-hand weapon": "Weapon 1H",
        "two-handed weapons": "Weapon 2H",
    },
    "unholy-death-knight": {
        "off hand weapons": "Off hand",
        "main hand weapons": "Weapon",
        "off-hand weapon": "Off hand",
        "main-hand weapon": "Weapon",
    },
    "balance-druid": {
        "off-hand weapons": "Off hand",
        "main hand weapons": "Weapon 1H",
        "two-handed weapons": "Weapon 2H",
        "off-hand weapon": "Off hand",
        "off-hand items": "Off hand",
        "main-hand weapon": "Weapon 1H",
    },
    "guardian-druid": {
        "weapons": "Weapon",
        "two handed weapons": "Weapon",
        "two-handed weapons": "Weapon",
        "weapon": "Weapon",
        "defensive trinkets": "Trinket",
        "offensive trinkets": "Trinket Off",
    },
    "feral-druid": {
        "two handed weapons": "Weapon",
        "two-handed weapons": "Weapon",
        "weapons": "Weapon",
        "weapon": "Weapon",
    },
    "restoration-druid": {
        "off hand weapons": "Off hand",
        "main hand weapons": "Weapon 1H",
        "two-handed weapons": "Weapon 2H",
        "two hand weapon": "Weapon 2H",
        "staff weapons": "Weapon 2H",
        "off-hand": "Off hand",
        "off hands": "Off hand",
        "main-hand weapon": "Weapon 1H",
    },
    "beast-mastery-hunter": {
        "one-handed weapons": "Weapon 1H",
        "two-hand weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 2H",
        "melee weapons": "Weapon",
    },
    "marksmanship-hunter": {
        "one-handed weapons": "Weapon 1H",
        "two-hand weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 2H",
        "melee weapons": "Weapon",
    },
    "survival-hunter": {
        "one-handed weapons": "Weapon 1H",
        "two-hand weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 2H",
        "melee weapons": "Weapon",
    },
    "arcane-mage": {
        "off hand weapons": "Off hand",
        "off-hand weapon": "Off hand",
        "main-hand weapons": "Weapon 1H",
        "two-handed weapons": "Weapon 2H",
        "two-handed  weapons": "Weapon 2H",
        "main-hand & two-handed weapons": "Weapon",
        "main-hand and two-handed weapons": "Weapon",
    },
    "fire-mage": {
        "off hand weapons": "Off hand",
        "off-hand weapon": "Off hand",
        "main-hand weapons": "Weapon 1H",
        "two-handed weapons": "Weapon 2H",
        "two-handed  weapons": "Weapon 2H",
        "main-hand & two-handed weapons": "Weapon",
        "main-hand and two-handed weapons": "Weapon",
    },
    "frost-mage": {
        "off hand weapons": "Off hand",
        "off-hand weapon": "Off hand",
        "main-hand weapons": "Weapon 1H",
        "two-handed weapons": "Weapon 2H",
        "two-handed  weapons": "Weapon 2H",
        "main-hand & two-handed weapons": "Weapon",
        "main-hand and two-handed weapons": "Weapon",
    },
    "holy-paladin": {
        "main-hand weapons": "Weapon",
        "shields and off-hands": "Off hand",
        "main-hand weapon": "Weapon",
        "shield": "Off hand",
        "off hands and shields": "Off hand",
        "off-hands and shields": "Off hand",
        "main hand weapons": "Weapon",
    },
    "protection-paladin": {
        "weapons": "Weapon",
        "shields": "Off hand",
        "main-hand weapon": "Weapon",
        "shield": "Off hand",
        "weapons and offhands": "Weapon",
    },
    "retribution-paladin": {
        "main-hand weapon": "Weapon",
        "two hand weapons": "Weapon",
        "two-handed weapons": "Weapon",
        "two-hand weapon": "Weapon",
        "weapon": "Weapon"
    },
    "discipline-priest": {
        "off-hands": "Off hand",
        "off-hand weapon": "Off hand",
        "staves": "Weapon 2H",
        "main hand weapons": "Weapon 1H",
    },
    "holy-priest": {
        "off-hands": "Off hand",
        "off-hand weapon": "Off hand",
        "staves": "Weapon 2H",
        "main hand weapons": "Weapon 1H",
    },
    "shadow-priest": {
        "off-hands": "Off hand",
        "off-hand weapon": "Off hand",
        "staves": "Weapon 2H",
        "main hand weapons": "Weapon 1H",
    },
    "assassination-rogue": {
        "weapons": "Weapon",
        "main-hand weapon": "Weapon",
        "main hand weapons": "Weapon",
        "off-hand weapon": "Weapon",
        "off hand weapons": "Off hand",
        "guns, bows, and thrown weapons": "Ranged"
    },
    "combat-rogue": {
        "off hand weapons": "Off hand",
        "main hand weapons": "Weapon",
        "off-hand weapon": "Off hand",
        "main-hand weapon": "Weapon",
        "guns, bows, and thrown weapons": "Ranged"
    },
    "subtlety-rogue": {
        "off hand weapons": "Off hand",
        "main hand weapons": "Weapon",
        "off-hand weapon": "Off hand",
        "main-hand weapon": "Weapon",
        "guns, bows, and thrown weapons": "Ranged"
    },
    "elemental-shaman": {
        "off hands": "Off hand",
        "staff weapons": "Weapon 2H",
        "main hand weapons": "Weapon 1H",
    },
    "enhancement-shaman": {
        "weapons": "Weapon",
        "main-hand weapon": "Weapon",
        "off-hand weapon": "Weapon",
    },
    "restoration-shaman": {
        "off hands": "Off hand",
        "staff weapons": "Weapon 2H",
        "main hand weapons": "Weapon 1H",
    },
    "affliction-warlock": {
        "offhand": "Off hand",
        "1-handed weapons": "Weapon 1H",
        "2-handed weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 2H",
        "weapon": "Weapon 2H",
        "off-hand weapon": "Off hand"
    },
    "demonology-warlock": {
        "offhand": "Off hand",
        "1-handed weapons": "Weapon 1H",
        "2-handed weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 2H",
        "weapon": "Weapon 2H",
        "off-hand weapon": "Off hand"
    },
    "destruction-warlock": {
        "off-hand weapon": "Off hand",
        "offhand": "Off hand",
        "1-handed weapons": "Weapon 1H",
        "2-handed weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 1H",
        "weapon": "Weapon 2H",
        "main-hand": "Weapon 1H",
        "off-hand": "Off hand"
    },
    "arms-warrior": {
        "two handed weapons": "Weapon",
        "main-hand weapon": "Weapon",
    },
    "fury-warrior": {
        "two handed weapons": "Weapon 2H",
        "main-hand weapon": "Weapon 1H",
        "off-hand weapon": "Weapon",
        "one handed weapons": "Weapon 1H",
        "duel wield weapons": "Weapon 1H",
    },
    "protection-warrior": {
        "shields": "Off hand",
        "main hand weapons": "Weapon",
        "shield": "Off hand",
        "main-hand weapon": "Weapon",
        "ranged weapons": "Ranged",
    },
}
