specs = [
    "blood-tank-death-knight",
    "frost-death-knight",
    "unholy-death-knight",
    "blood-dps-death-knight",
    "balance-druid",
    "feral-tank-druid",
    "feral-dps-druid",
    "restoration-druid",
    "beast-mastery-hunter",
    "marksmanship-hunter",
    "survival-hunter",
    "arcane-mage",
    "fire-mage",
    "frost-mage",
    "holy-paladin",
    "protection-paladin",
    "retribution-paladin",
    "discipline-priest",
    "holy-priest",
    "shadow-priest",
    "assassination-rogue",
    "combat-rogue",
    "elemental-shaman",
    "enhancement-shaman",
    "restoration-shaman",
    "affliction-warlock",
    "demonology-warlock",
    "destruction-warlock",
    "arms-warrior",
    "fury-warrior",
    "protection-warrior",
]

spec_to_url_path = {
    "blood-tank-death-knight": "death-knight/blood/tank",
    "frost-death-knight": "death-knight/frost/dps",
    "unholy-death-knight": "death-knight/unholy/dps",
    "blood-dps-death-knight": "death-knight/blood/dps",
    "balance-druid": "druid/balance/dps",
    "feral-tank-druid": "druid/feral/tank",
    "feral-dps-druid": "druid/feral/dps",
    "restoration-druid": "druid/restoration/healer",
    "beast-mastery-hunter": "hunter/beast-mastery/dps",
    "marksmanship-hunter": "hunter/marksmanship/dps",
    "survival-hunter": "hunter/survival/dps",
    "arcane-mage": "mage/arcane/dps",
    "fire-mage": "mage/fire/dps",
    "frost-mage": "mage/frost/dps",
    "holy-paladin": "paladin/holy/healer",
    "protection-paladin": "paladin/protection/tank",
    "retribution-paladin": "paladin/retribution/dps",
    "discipline-priest": "priest/discipline/healer",
    "holy-priest": "priest/holy/healer",
    "shadow-priest": "priest/shadow/dps",
    "assassination-rogue": "rogue/assassination/dps",
    "combat-rogue": "rogue/combat/dps",
    "subtlety-rogue": "rogue/subtlety/dps",
    "elemental-shaman": "shaman/elemental/dps",
    "enhancement-shaman": "shaman/enhancement/dps",
    "restoration-shaman": "shaman/restoration/healer",
    "affliction-warlock": "warlock/affliction/dps",
    "demonology-warlock": "warlock/demonology/dps",
    "destruction-warlock": "warlock/destruction/dps",
    "arms-warrior": "warrior/arms/dps",
    "fury-warrior": "warrior/fury/dps",
    "protection-warrior": "warrior/protection/tank"
}
