slots = {
    "Head": 0,
    "Neck": 1,
    "Shoulder": 2,
    "Back": 3,
    "Chest": 4,
    "Wrist": 5,
    "Hands": 6,
    "Waist": 7,
    "Legs": 8,
    "Feet": 9,
    "Finger": 10,
    "Trinket": 11,
    "Trinket Off": 12,
    "Weapon": 13,
    "Weapon 1H": 14,
    "Off hand": 15,
    "Weapon 2H": 16,
    "Ranged": 17,
    "Relic": 18
}

bdk_planner_slots = {
    1: "Head",
    2: "Neck",
    3: "Shoulder",
    15: "Back",
    5: "Chest",
    9: "Wrist",
    10: "Hands",
    6: "Waist",
    7: "Legs",
    8: "Feet",
    11: "Finger",
    12: "Finger",
    13: "Trinket",
    14: "Trinket",
    16: "Weapon",
    18: "Relic"
}
