specs = [
    "blood-tank-death-knight",
    "frost-death-knight",
    "unholy-death-knight",
    "balance-druid",
    "feral-tank-druid",
    "feral-dps-druid",
    "restoration-druid",
    "beast-mastery-hunter",
    "marksmanship-hunter",
    "survival-hunter",
    "arcane-mage",
    "fire-mage",
    "frost-mage",
    "brewmaster-monk",
    "mistweaver-monk",
    "windwalker-monk",
    "holy-paladin",
    "protection-paladin",
    "retribution-paladin",
    "discipline-priest",
    "holy-priest",
    "shadow-priest",
    "assassination-rogue",
    "combat-rogue",
    "subtlety-rogue",
    "elemental-shaman",
    "enhancement-shaman",
    "restoration-shaman",
    "affliction-warlock",
    "demonology-warlock",
    "destruction-warlock",
    "arms-warrior",
    "fury-warrior",
    "protection-warrior"
]

spec_to_class = {
    "blood-tank-death-knight": "Death knight",
    "frost-death-knight": "Death knight",
    "unholy-death-knight": "Death knight",
    "balance-druid": "Druid",
    "feral-tank-druid": "Druid",
    "feral-dps-druid": "Druid",
    "restoration-druid": "Druid",
    "beast-mastery-hunter": "Hunter",
    "marksmanship-hunter": "Hunter",
    "survival-hunter": "Hunter",
    "arcane-mage": "Mage",
    "fire-mage": "Mage",
    "frost-mage": "Mage",
    "brewmaster-monk": "Monk",
    "mistweaver-monk": "Monk",
    "windwalker-monk": "Monk",
    "holy-paladin": "Paladin",
    "protection-paladin": "Paladin",
    "retribution-paladin": "Paladin",
    "discipline-priest": "Priest",
    "holy-priest": "Priest",
    "shadow-priest": "Priest",
    "assassination-rogue": "Rogue",
    "combat-rogue": "Rogue",
    "subtlety-rogue": "Rogue",
    "elemental-shaman": "Shaman",
    "enhancement-shaman": "Shaman",
    "restoration-shaman": "Shaman",
    "affliction-warlock": "Warlock",
    "demonology-warlock": "Warlock",
    "destruction-warlock": "Warlock",
    "arms-warrior": "Warrior",
    "fury-warrior": "Warrior",
    "protection-warrior": "Warrior"
}

spec_to_spec_name = {
    "blood-tank-death-knight": "Blood tank",
    "frost-death-knight": "Frost",
    "unholy-death-knight": "Unholy",
    "balance-druid": "Balance",
    "feral-tank-druid": "Feral tank",
    "feral-dps-druid": "Feral dps",
    "restoration-druid": "Restoration",
    "beast-mastery-hunter": "Beast mastery",
    "marksmanship-hunter": "Marksmanship",
    "survival-hunter": "Survival",
    "arcane-mage": "Arcane",
    "fire-mage": "Fire",
    "frost-mage": "Frost",
    "brewmaster-monk": "Brewmaster",
    "mistweaver-monk": "Mistweaver",
    "windwalker-monk": "Windwalker",
    "holy-paladin": "Holy",
    "protection-paladin": "Protection",
    "retribution-paladin": "Retribution",
    "discipline-priest": "Discipline",
    "holy-priest": "Holy",
    "shadow-priest": "Shadow",
    "assassination-rogue": "Assassination",
    "combat-rogue": "Combat",
    "subtlety-rogue": "Subtlety",
    "elemental-shaman": "Elemental",
    "enhancement-shaman": "Enhancement",
    "restoration-shaman": "Restoration",
    "affliction-warlock": "Affliction",
    "demonology-warlock": "Demonology",
    "destruction-warlock": "Destruction",
    "arms-warrior": "Arms",
    "fury-warrior": "Fury",
    "protection-warrior": "Protection"
}
