specs = [
    "blood-tank-death-knight",
    "frost-death-knight",
    "unholy-death-knight",
    "balance-druid",
    "feral-tank-druid",
    "feral-dps-druid",
    "restoration-druid",
    "beast-mastery-hunter",
    "marksmanship-hunter",
    "survival-hunter",
    "arcane-mage",
    "fire-mage",
    "frost-mage",
    "holy-paladin",
    "protection-paladin",
    "retribution-paladin",
    "discipline-priest",
    "holy-priest",
    "shadow-priest",
    "assassination-rogue",
    "combat-rogue",
    "subtlety-rogue",
    "elemental-shaman",
    "enhancement-shaman",
    "restoration-shaman",
    "affliction-warlock",
    "demonology-warlock",
    "destruction-warlock",
    "arms-warrior",
    "fury-warrior",
    "protection-warrior",
]


